INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0108', 'T01', '걷기 좋은 코스 🌼', NULL, NULL, 8, 'Y', 'JJ', 'Yellow wave 🌼');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0107', 'T01', '인기 여행지 🔍', NULL, NULL, 7, 'Y', 'JJ', 'Popular Spots 🔍');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0106', 'T01', 'K-콘텐츠에 열광하라📺', NULL, NULL, 6, 'Y', 'JJ', 'Get excited about K-content 📺');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0105', 'T01', '로컬브랜드, 여행이 되다', NULL, NULL, 5, 'Y', 'JJ', 'Local brands, becoming a travel trend');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0104', 'T01', '제주인이 말하는 힐링', NULL, NULL, 4, 'Y', 'JJ', 'What Jeju people say about healing');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0103', 'T01', '모든 날, 모든 순간 함께', NULL, NULL, 3, 'Y', 'JJ', 'Let''s be together, every day, every moment');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0102', 'T01', '여행을 더 달콤하게 🍯', NULL, NULL, 2, 'Y', 'JJ', 'Let''s all share some tips! 🍯');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0101', 'T01', '이벤트', NULL, NULL, 1, 'Y', 'JJ', 'Event');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011302', 'A0113', 'WHO', NULL, '#808080', 2, 'Y', 'JJ', 'WHO');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011301', 'A0113', 'ECO', NULL, '#808080', 1, 'Y', 'JJ', 'ECO');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011204', 'A0112', '스페이스', NULL, '#808080', 4, 'Y', 'JJ', 'Space');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M0320', 'M03', '여행글', '', '', 2, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M0310', 'M03', '설명글', '', '', 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M03', '', '품질 관리 대상', '', '', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M0220', 'M02', '추천 배너', '', '', 2, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M0210', 'M02', '추천 포스트', '', '', 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M02', '', '교체 주기 관리 대상', '', '', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M0140', 'M01', '겨울', '', '', 4, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M0130', 'M01', '가을', '', '', 3, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M0120', 'M01', '여름', '', '', 2, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M0110', 'M01', '봄', '', '', 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('M01', '', '계절코드', '', '', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G0204', 'G02', '로컬브랜드 프리미엄', NULL, NULL, 4, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G0203', 'G02', '로컬브랜드 라이트', NULL, NULL, 3, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G0202', 'G02', '라이트', NULL, NULL, 2, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G0201', 'G02', '프리', NULL, NULL, 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011203', 'A0112', '스토어', NULL, '#808080', 3, 'Y', 'JJ', 'Store');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011202', 'A0112', '음식점', NULL, '#808080', 2, 'Y', 'JJ', 'Restaurant');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G02', NULL, '로컬브랜드 등급', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011201', 'A0112', '카페', NULL, '#808080', 1, 'Y', 'JJ', 'Café ');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0112', 'A01', '로컬브랜드', NULL, '#d1c68e', 9, 'Y', 'JJ', 'Local Brands');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A01', NULL, '관광지카테고리', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A02', NULL, '위치', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0201', 'A02', '제주시', NULL, NULL, NULL, 'Y', 'JJ', 'Jeju-si');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0202', 'A02', '서귀포시', NULL, NULL, NULL, 'Y', 'JJ', 'Seogwipo-si');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A03', NULL, '동반유형', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0301', 'A03', '휠체어', NULL, NULL, NULL, 'Y', 'JJ', 'Wheelchair');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0302', 'A03', '노약자', NULL, NULL, NULL, 'Y', 'JJ', 'Elderly');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0303', 'A03', '어린이', NULL, NULL, NULL, 'Y', 'JJ', 'Children');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0399', 'A03', '해당없음', NULL, NULL, NULL, 'Y', 'JJ', 'None');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Z01', NULL, 'FAQ카테고리', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Z0101', 'Z01', '이용방법', NULL, NULL, NULL, 'Y', 'JJ', 'How to Use');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Z0102', 'Z01', '회원정보', NULL, NULL, NULL, 'Y', 'JJ', 'Profile');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Z0103', 'Z01', '제휴문의', NULL, NULL, NULL, 'Y', 'JJ', 'Partnership Inquiry');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Z0104', 'Z01', '오류문의', NULL, NULL, NULL, 'Y', 'JJ', 'Report Error');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('S01', NULL, '인터뷰이 Link', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('S0101', 'S01', '페이스북', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('S0102', 'S01', '인스타그램', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('S0103', 'S01', '유튜브', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('S0104', 'S01', '홈페이지', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('S0105', 'S01', '블로그', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('S0106', 'S01', '기타 SNS', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('S0107', 'S01', '기타', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020101', 'A0201', '제주시', NULL, NULL, 1, 'Y', 'JJ', 'Jeju-si');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020102', 'A0201', '한경면', NULL, NULL, 1, 'Y', 'JJ', 'Hangyeong-myeo');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020103', 'A0201', '한림읍', NULL, NULL, 1, 'Y', 'JJ', 'Hallim-eup');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020104', 'A0201', '애월읍', NULL, NULL, 1, 'Y', 'JJ', 'Aewol-eup');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020105', 'A0201', '조천읍', NULL, NULL, 1, 'Y', 'JJ', 'Jocheon-eup');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020106', 'A0201', '구좌읍', NULL, NULL, 1, 'Y', 'JJ', 'Gujwa-eup');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020107', 'A0201', '한라산', NULL, NULL, 1, 'Y', 'JJ', 'Hallasan');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020108', 'A0201', '우도', NULL, NULL, 1, 'Y', 'JJ', 'Udo Island');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020201', 'A0202', '서귀포시', NULL, NULL, 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020202', 'A0202', '대정읍', NULL, NULL, 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020203', 'A0202', '안덕면', NULL, NULL, 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020204', 'A0202', '남원읍', NULL, NULL, 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020205', 'A0202', '표선면', NULL, NULL, 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020206', 'A0202', '성산읍', NULL, NULL, 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020207', 'A0202', '한라산', NULL, NULL, 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A020208', 'A0202', '우도', NULL, NULL, 1, 'Y', 'JJ', 'Udo Island');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('U01', NULL, '권한', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('U0101', 'U01', 'Admin', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('U0102', 'U01', 'Manager', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('U0103', 'U01', 'Editor', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('U0104', 'U01', 'Operater', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('U0105', 'U01', 'Data', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0101', 'A01', '오름', NULL, '#FF0000', 1, 'Y', 'JJ', 'Oreum');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0102', 'A01', '바다', NULL, '#0100FF', 2, 'Y', 'JJ', 'Ocean');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0103', 'A01', '숲', NULL, '#1DDB16', 3, 'Y', 'JJ', 'Forests');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0104', 'A01', '한라산', NULL, '#FFBB00', 4, 'Y', 'JJ', 'Hallasan');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0105', 'A01', '마을', NULL, '#5F00FF', 5, 'Y', 'JJ', 'Villages');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0106', 'A01', '길', NULL, '#FF0000', 6, 'Y', 'JJ', 'Roads');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0107', 'A01', '섬', NULL, '#0100FF', 7, 'Y', 'JJ', 'Islands');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0108', 'A01', '제주유산', NULL, '#FFBB00', 8, 'Y', 'JJ', 'Jeju Heritage');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0109', 'A01', '독립서점', NULL, '#4641D9', 10, 'Y', 'JJ', 'Independent Bookstores');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0110', 'A01', '민속시장', NULL, '#1DDB16', 11, 'Y', 'JJ', 'Traditional Markets');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0111', 'A01', '문화생활', NULL, '#5F00FF', 12, 'Y', 'JJ', 'Cultural Activities');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010101', 'A0101', '탐방로오름', NULL, NULL, 1, 'Y', 'JJ', 'Oreum with Scenic Trail');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010102', 'A0101', '경관지정 오름', NULL, NULL, 2, 'Y', 'JJ', 'Oreum Designated as Natural Wonder');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010103', 'A0101', '굼부리오름', NULL, NULL, 3, 'Y', 'JJ', 'Oreum with Crater');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010104', 'A0101', '한라산 권역오름', NULL, NULL, 4, 'Y', 'JJ', 'Oreum Within Hallasan Region');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010201', 'A0102', '해수욕장', NULL, NULL, 2, 'Y', 'JJ', 'Beach ');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010202', 'A0102', '해변', NULL, NULL, 1, 'Y', 'JJ', 'Shore ');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010203', 'A0102', '포구', NULL, NULL, 3, 'Y', 'JJ', 'Port');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010301', 'A0103', '휴양림', NULL, NULL, 1, 'Y', 'JJ', 'Recreational Forest ');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010302', 'A0103', '곶자왈', NULL, NULL, 2, 'Y', 'JJ', 'Gotjawal Forest');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010303', 'A0103', '숲 산책길', NULL, NULL, 3, 'Y', 'JJ', 'Forest Trail');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010401', 'A0104', '탐방코스', NULL, NULL, 1, 'Y', 'JJ', 'Exploration Course');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010402', 'A0104', '탐방로 관광지', NULL, NULL, 2, 'Y', 'JJ', 'Tourist Attraction on the Trail');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010501', 'A0105', '초록마을', NULL, NULL, 1, 'Y', 'JJ', 'Green Village');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010502', 'A0105', '바다마을', NULL, NULL, 2, 'Y', 'JJ', 'Sea Village');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010503', 'A0105', '문화마을', NULL, NULL, 3, 'Y', 'JJ', 'Culture Village');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010601', 'A0106', '올레길 코스', NULL, NULL, 1, 'Y', 'JJ', 'Olle Trail Course');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0101', 'C01', '휴식', NULL, '#ff0000', 2, 'Y', 'JJ', 'Resting');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0103', 'C01', '트래킹', NULL, '#00ff00', 3, 'Y', 'JJ', 'Trekking');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0104', 'C01', '같이가치제주', NULL, '#c24444', 4, 'Y', 'JJ', 'Better Together, Jeju');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0105', 'C01', '사용자', NULL, '#b37870', 5, 'Y', 'JJ', 'User');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020401', 'P02', '안전지도날씨', '201', 'WEATHER', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020402', 'P02', '안전지도의료-병원', '201', 'HOSPITAL', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020403', 'P02', '안전지도의료-약국', '201', 'PHARMACY', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020404', 'P02', '안전지도의료-보건소', '201', 'PUBLIC_HEALTh', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020405', 'P02', '안전지도편의-화장실', '201', 'TOILET', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020406', 'P02', '안전지도편의-편의점', '201', 'CONVENIENCE_STORE', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020407', 'P02', '안전지도편의-버스정류장', '201', 'BUS_STATION', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020408', 'P02', '안전지도안전-CCTV', '201', 'CCTV', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020409', 'P02', '안전지도안전-비상벨', '201', 'EMERGENCY_BELL', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020410', 'P02', '안전지도안전-파출소', '201', 'POLICE_BOX', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020411', 'P02', '안전지도안전-소방서', '201', 'FIRE_STATION', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020412', 'P02', '안전지도충전-전기차', '201', 'ELECTRIC_CAR', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020413', 'P02', '안전지도충전-전기휠체어', '201', 'ELECTRIC_WHEELCHAIR', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020414', 'P02', '안전지안전지도충전-LPG', '201', 'LPG', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020415', 'P02', '안전지도사고-교통', '201', 'TRAFFIC_ACCIDENT_SECTION', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020416', 'P02', '안전지도사고-자전거', '201', 'BICYCLE_ACCIDENT', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020417', 'P02', '안전지도사고-보행자', '201', 'PEDESTRIAN_ACCIDENT_DAY', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020418', 'P02', '안전지도사고-바다', '201', 'WATER_ACCIDENT', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020419', 'P02', '안전지도사고-산', '201', 'MOUNTAIN_ACCIDENT', NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020110', 'P02', '관광지', '400', NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020120', 'P02', '관광지 시설정보', '401', NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020210', 'P02', '포스트', '300', NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P020220', 'P02', '포스트 시설정보', '301', NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('R01', NULL, '신고사유', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('R0101', 'R01', '잘못된 글입니다', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('R0102', 'R01', '허위글입니다', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('R0103', 'R01', '비방과 욕설이 심합니다', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('R0199', 'R01', '기타', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0205', 'L02', '운영시간', NULL, NULL, NULL, 'Y', 'JJ', 'Operating Hours');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L01', NULL, '식당/숙박', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0101', 'L01', '식당', NULL, NULL, NULL, 'Y', 'JJ', 'Restaurant');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010101', 'L0101', '한식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010102', 'L0101', '일식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010103', 'L0101', '중식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010104', 'L0101', '양식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010105', 'L0101', '멕시코음식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010106', 'L0101', '스페인음식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010107', 'L0101', '아시아음식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010108', 'L0101', '이탈리아음식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010109', 'L0101', '인도음식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010110', 'L0101', '프랑스음식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010111', 'L0101', '퓨전음식', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010112', 'L0101', '푸드코트', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010113', 'L0101', '카페', NULL, NULL, NULL, 'Y', 'JJ', 'Café ');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010114', 'L0101', '베이커리', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010115', 'L0101', '떡집', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0102', 'L01', '숙박', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010201', 'L0102', '호텔', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010202', 'L0102', '리조트', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010203', 'L0102', '펜션', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010204', 'L0102', '호스텔', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010205', 'L0102', '게스트하우스', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L010207', 'L0102', '카페', NULL, NULL, NULL, 'Y', 'JJ', 'Café ');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L02', NULL, '식당/숙박 시설정보', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0201', 'L02', '주소', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0202', 'L02', '전화번호', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0203', 'L02', '가격', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0204', 'L02', '옵션', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0206', 'L02', '유형', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0207', 'L02', '수용인원', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('L0208', 'L02', '키워드', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010602', 'A0106', '올레길 관광지', NULL, NULL, 2, 'Y', 'JJ', 'Tourist Attraction on the Olle Trail');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010603', 'A0106', '길 탐방', NULL, NULL, 3, 'Y', 'JJ', 'Street Exploration');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010701', 'A0107', '우도', NULL, NULL, 1, 'Y', 'JJ', 'Udo');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010702', 'A0107', '가파도', NULL, NULL, 2, 'Y', 'JJ', 'Gapado');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010703', 'A0107', '마라도', NULL, NULL, 3, 'Y', 'JJ', 'Marado');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010704', 'A0107', '추자도', NULL, NULL, 4, 'Y', 'JJ', 'Chujado');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010705', 'A0107', '섬 탐방', NULL, NULL, 5, 'Y', 'JJ', 'Island Exploration');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010801', 'A0108', '자연유산', NULL, NULL, 1, 'Y', 'JJ', 'Natural Heritage');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010802', 'A0108', '문화재', NULL, NULL, 2, 'Y', 'JJ', 'Cultural Property');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010803', 'A0108', '자연탐방', NULL, NULL, 3, 'Y', 'JJ', 'Nature Exploration');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010901', 'A0109', '서점', NULL, NULL, 1, 'Y', 'JJ', 'Bookstore');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A010902', 'A0109', '북카페', NULL, NULL, 2, 'Y', 'JJ', 'Book Café');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011001', 'A0110', '전통 오일장', NULL, NULL, 1, 'Y', 'JJ', 'Fifth-Day Market');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011002', 'A0110', '전통 매일시장', NULL, NULL, 2, 'Y', 'JJ', 'Everyday Market');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011101', 'A0111', '역사', NULL, NULL, 1, 'Y', 'JJ', 'History');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011102', 'A0111', '공원', NULL, NULL, 2, 'Y', 'JJ', 'Park');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011103', 'A0111', '미술관&박물관', NULL, NULL, 3, 'Y', 'JJ', 'Gallery & Museum');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C01', NULL, '코스메뉴', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W91', NULL, '하늘상태+강수형태', NULL, NULL, 0, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9110', 'W91', '맑음', '10', NULL, 1, 'Y', 'JJ', 'Sunny');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9111', 'W91', '맑고 비', '11', NULL, 2, 'Y', 'JJ', 'Sunny with Rain');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9112', 'W91', '맑고 비/눈', '12', NULL, 3, 'Y', 'JJ', 'Sunny with Rain/Snow');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9113', 'W91', '맑고 눈', '13', NULL, 4, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9114', 'W91', '맑고 소나기', '14', NULL, 5, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9115', 'W91', '맑고 빗방울', '15', NULL, 6, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9116', 'W91', '맑고 빗방울/눈날림', '16', NULL, 7, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9117', 'W91', '맑고 눈날림', '17', NULL, 8, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9130', 'W91', '구름많음', '30', NULL, 9, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9131', 'W91', '구름많고 비', '31', NULL, 10, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9132', 'W91', '구름많고 비/눈', '32', NULL, 11, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9133', 'W91', '구름많고 눈', '33', NULL, 12, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9134', 'W91', '구름많고 소나기', '34', NULL, 13, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9135', 'W91', '구름많고 빗방울', '35', NULL, 14, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9136', 'W91', '구름많고 빗방울/눈날림', '36', NULL, 15, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9137', 'W91', '구름많고 눈날림', '37', NULL, 16, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9140', 'W91', '흐림', '40', NULL, 17, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9141', 'W91', '흐리고 비', '41', NULL, 18, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9142', 'W91', '흐리고 비/눈', '42', NULL, 19, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9143', 'W91', '흐리고 눈', '43', NULL, 20, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9144', 'W91', '흐리고 소나기', '44', NULL, 21, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9145', 'W91', '흐리고 빗방울', '45', NULL, 22, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9146', 'W91', '흐리고 빗방울/눈날림', '46', NULL, 23, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('W9147', 'W91', '흐리고 눈날림', '47', NULL, 24, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G01', NULL, '회원등급', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G0101', 'G01', '일반', NULL, '#ff0000', 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G0102', 'G01', '프리미엄', NULL, '#00ff00', 2, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G0103', 'G01', '코스마스터', NULL, '#0000ff', 3, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('G0104', 'G01', '입문', NULL, '#e38d8d', 4, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Q01', NULL, '1:1문의', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Q0101', 'Q01', '회원가입 및 개인정보문의', NULL, NULL, 1, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Q0102', 'Q01', '서비스 관련 문의', NULL, NULL, 2, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Q0103', 'Q01', '불편 및 장애제보', NULL, NULL, 3, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Q0104', 'Q01', '제휴 문의', NULL, NULL, 4, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Q0105', 'Q01', '기타 문의', NULL, NULL, 5, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P01', NULL, '푸시 관련정보', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P0102', 'P01', '시설정보', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P0101', 'P01', '날씨', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('U0199', 'U01', 'Developer', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('D01', NULL, '탈퇴 사유', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('D0101', 'D01', '재가입으로 인한 탈퇴', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('D0102', 'D01', '타 어플 유사서비스 이용', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('D0103', 'D01', '콘텐츠 내용 부족', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('D0104', 'D01', '서비스 이용 불편', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('D0105', 'D01', '자주 이용하지 않음', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('P02', NULL, '연결화면', NULL, NULL, NULL, 'Y', 'JJ', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Z02', NULL, '지역구분', NULL, NULL, NULL, 'Y', NULL, NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Z0201', 'Z02', '제주', 'JJ', 'A02', 1, 'Y', 'JJ', 'Jeju');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Z0202', 'Z02', '하노이', 'HN', 'A04', 2, 'Y', 'HN', 'Hanoi');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0401', 'A04', '하노이', NULL, NULL, NULL, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040101', 'A0401', '선떠이 ', NULL, NULL, 1, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0402', 'A04', '하이퐁', NULL, NULL, 1, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0403', 'A04', '라오까이', NULL, NULL, 1, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0404', 'A04', '닌빈', NULL, NULL, 1, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0405', 'A04', '꽝닌', NULL, NULL, 1, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040201', 'A0402', '즈엉낀', NULL, NULL, 1, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040202', 'A0402', '도선', NULL, NULL, 2, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040203', 'A0402', '하이안', NULL, NULL, 3, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040204', 'A0402', '끼엔안', NULL, NULL, 4, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040205', 'A0402', '홍방', NULL, NULL, 5, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040206', 'A0402', '응오꾸옌', NULL, NULL, 6, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040207', 'A0402', '레쩐', NULL, NULL, 7, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040208', 'A0402', '안즈엉', NULL, NULL, 8, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040209', 'A0402', '안라오', NULL, NULL, 9, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040210', 'A0402', '박롱비', NULL, NULL, 10, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040211', 'A0402', '끼엔투이', NULL, NULL, 11, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040212', 'A0402', '띠엔랑', NULL, NULL, 12, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040213', 'A0402', '빈바오', NULL, NULL, 13, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040214', 'A0402', '투이응우옌', NULL, NULL, 14, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040215', 'A0402', '깟하이', NULL, NULL, 15, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040102', 'A0401', '바딘', NULL, NULL, 2, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040103', 'A0401', '꺼우저이', NULL, NULL, 3, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040104', 'A0401', '동다', NULL, NULL, 4, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040105', 'A0401', '하이바쯩', NULL, NULL, 5, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040106', 'A0401', '하동', NULL, NULL, 6, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040107', 'A0401', '호안끼엠', NULL, NULL, 7, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040108', 'A0401', '호앙마이', NULL, NULL, 8, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040109', 'A0401', '롱비엔', NULL, NULL, 9, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040110', 'A0401', '서호', NULL, NULL, 10, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040111', 'A0401', '타인쑤언', NULL, NULL, 11, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040112', 'A0401', '박뜨리엠', NULL, NULL, 12, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040113', 'A0401', '남뜨리엠', NULL, NULL, 13, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040114', 'A0401', '바비', NULL, NULL, 14, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040115', 'A0401', '쯔엉미', NULL, NULL, 15, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040116', 'A0401', '단푸엉', NULL, NULL, 16, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040117', 'A0401', '동아인', NULL, NULL, 17, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040118', 'A0401', '자럼', NULL, NULL, 18, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040119', 'A0401', '호아이득', NULL, NULL, 19, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040120', 'A0401', '멜린', NULL, NULL, 20, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040121', 'A0401', '미득', NULL, NULL, 21, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040122', 'A0401', '푸쑤옌', NULL, NULL, 22, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040123', 'A0401', '푹토', NULL, NULL, 23, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040124', 'A0401', '꾸옥오아이', NULL, NULL, 24, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040125', 'A0401', '속선', NULL, NULL, 25, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040126', 'A0401', '탁텟', NULL, NULL, 26, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040127', 'A0401', '타인오아이', NULL, NULL, 27, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040128', 'A0401', '타인찌 ', NULL, NULL, 28, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040129', 'A0401', '트엉띤 ', NULL, NULL, 29, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040130', 'A0401', '응호아 ', NULL, NULL, 30, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040301', 'A0403', '사빠', NULL, NULL, 1, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040302', 'A0403', '박하', NULL, NULL, 2, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040303', 'A0403', '바오탕', NULL, NULL, 3, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040304', 'A0403', '바오옌', NULL, NULL, 4, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040305', 'A0403', '밧쌋', NULL, NULL, 5, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040306', 'A0403', '므엉크엉', NULL, NULL, 6, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040307', 'A0403', '시마까이', NULL, NULL, 7, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040308', 'A0403', '반반', NULL, NULL, 8, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040401', 'A0404', '닌빈', NULL, NULL, 1, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040402', 'A0404', '땀디엡', NULL, NULL, 2, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040403', 'A0404', '자비엔', NULL, NULL, 3, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040404', 'A0404', '호알르', NULL, NULL, 4, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040405', 'A0404', '낌선', NULL, NULL, 5, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040406', 'A0404', '뇨꽌', NULL, NULL, 6, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040407', 'A0404', '옌카인', NULL, NULL, 7, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040408', 'A0404', '옌모', NULL, NULL, 8, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040501', 'A0405', '할롱', NULL, NULL, 1, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040502', 'A0405', '몽까이', NULL, NULL, 2, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040503', 'A0405', '우옹비', NULL, NULL, 3, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040504', 'A0405', '껌파', NULL, NULL, 4, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040505', 'A0405', '꽝옌', NULL, NULL, 5, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040506', 'A0405', '동찌에우', NULL, NULL, 6, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040507', 'A0405', '꼬또', NULL, NULL, 7, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040508', 'A0405', '덤하', NULL, NULL, 8, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040509', 'A0405', '하이하', NULL, NULL, 9, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040510', 'A0405', '번돈', NULL, NULL, 10, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040511', 'A0405', '빈리에우', NULL, NULL, 11, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040512', 'A0405', '바째', NULL, NULL, 12, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A040513', 'A0405', '띠엔옌', NULL, NULL, 13, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A04', NULL, '하노이 위치', NULL, NULL, NULL, 'Y', 'HN', NULL);
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0108', 'C01', '사용자', NULL, '#b37870', 1, 'Y', 'HN', 'User');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0114', 'A01', '자연탐방', NULL, '#874444', 1, 'Y', 'HN', 'Nature Exploration');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011401', 'A0114', '바다&섬', NULL, '#808080', 1, 'Y', 'HN', 'Ocean&Island');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011402', 'A0114', '산', NULL, '#808080', 2, 'Y', 'HN', 'Mountain');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011403', 'A0114', '호수&강', NULL, '#808080', 3, 'Y', 'HN', 'Lake&River');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0115', 'A01', '문화생활', NULL, '#7a2121', 4, 'Y', 'HN', 'Cultural Activities');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011501', 'A0115', '공원', NULL, '#808080', 1, 'Y', 'HN', 'Park');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011502', 'A0115', '관람&전시', NULL, '#808080', 2, 'Y', 'HN', 'Show&Exhibition');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0116', 'A01', '현지체험', NULL, '#6b4646', 2, 'Y', 'HN', 'Local experience');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011601', 'A0116', '마을', NULL, '#808080', 1, 'Y', 'HN', 'Villages');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011602', 'A0116', '테마거리', NULL, '#808080', 2, 'Y', 'HN', 'Theme street');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011603', 'A0116', '트레킹', NULL, '#808080', 3, 'Y', 'HN', 'Trekking');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011604', 'A0116', '시장', NULL, '#808080', 4, 'Y', 'HN', 'Markets');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0117', 'A01', '로컬브랜드', NULL, '#8a3b3b', 5, 'Y', 'HN', 'Local Brand');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011701', 'A0117', '음식점', NULL, '#808080', 2, 'Y', 'HN', 'Restaurant');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011702', 'A0117', '카페', NULL, '#808080', 1, 'Y', 'HN', 'Café');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011703', 'A0117', '스페이스', NULL, '#808080', 3, 'Y', 'HN', 'Space');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0118', 'A01', '베트남 유산', NULL, '#b52626', 3, 'Y', 'HN', 'Vietnam Heritage');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011801', 'A0118', '자연유산', NULL, '#808080', 1, 'Y', 'HN', 'Natural Heritage');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011802', 'A0118', '역사유적', NULL, '#808080', 2, 'Y', 'HN', 'Historical remains');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0110', 'T01', 'test', NULL, NULL, 10, 'Y', 'HN', 'test');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0111', 'T01', 'test', NULL, NULL, 11, 'Y', 'HN', 'test');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0109', 'T01', '이벤트', NULL, NULL, 9, 'Y', 'HN', 'Event');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0112', 'T01', 'test', NULL, NULL, 12, 'Y', 'HN', 'test');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0113', 'T01', '로컬브랜드, 여행이 되다', NULL, NULL, 13, 'Y', 'HN', 'Local brands, becoming a travel trend');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0114', 'T01', '하노이 여행, 추억은 영원하길', NULL, NULL, 14, 'Y', 'HN', 'Trip to Hanoi, may memories last forever');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0115', 'T01', '일상을 여행처럼', NULL, NULL, 15, 'Y', 'HN', 'Everyday is like a trip');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0116', 'T01', '흥겨운 거리 속으로 🛤️', NULL, NULL, 16, 'Y', 'HN', 'Into the lively street 🛤️');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0121', 'T01', '로컬브랜드, 여행이 되다 : 책방 편 📚', NULL, NULL, 21, 'Y', 'SE', 'Local Brands, Becoming a Trip: Bookstore Edition 📚');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0119', 'A01', '랜드마크', NULL, '#FF0000', 1, 'Y', 'SE', 'Landmark');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011901', 'A0119', '공간', NULL, '', 1, 'Y', 'SE', 'Spaces');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A011902', 'A0119', '경관', NULL, '', 2, 'Y', 'SE', 'Sceneries');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0120', 'A01', '한강', NULL, '#0100FF', 2, 'Y', 'SE', 'Han River');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012001', 'A0120', '한강공원', NULL, '', 1, 'Y', 'SE', 'Han River Park');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0121', 'A01', '서울유산', NULL, '#1DDB16', 3, 'Y', 'SE', 'Cultural Heritage');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012101', 'A0121', '궁·능', NULL, '', 1, 'Y', 'SE', 'Palaces · Tombs');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012102', 'A0121', '유적', NULL, '', 2, 'Y', 'SE', 'Relics');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0122', 'A01', '식도락', NULL, '#FFBB00', 4, 'Y', 'SE', 'Gastronomy');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012201', 'A0122', '먹자골목', NULL, '', 1, 'Y', 'SE', 'Food Alleys');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0123', 'A01', '로컬브랜드', NULL, '#5F00FF', 10, 'Y', 'SE', 'Local Brand');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012301', 'A0123', '책방', NULL, '', 1, 'Y', 'SE', 'Book Shops');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012302', 'A0123', '카페', NULL, '', 2, 'Y', 'SE', 'Cafés');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012303', 'A0123', '음식점', NULL, '', 3, 'Y', 'SE', 'Restaurants');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012304', 'A0123', '상점', NULL, '', 4, 'Y', 'SE', 'Stores');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0124', 'A01', '전통생활', NULL, '#4641D9', 5, 'Y', 'SE', 'Traditional Living');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012401', 'A0124', '시장', NULL, '', 1, 'Y', 'SE', 'Markets');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012402', 'A0124', '마을', NULL, '', 2, 'Y', 'SE', 'Villages');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0125', 'A01', '문화예술', NULL, '#1DDB16', 6, 'Y', 'SE', 'Culture and Arts');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012501', 'A0125', '복합문화공간', NULL, '', 1, 'Y', 'SE', 'Complexes');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012502', 'A0125', '미술관', NULL, '', 2, 'Y', 'SE', 'Galleries');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012503', 'A0125', '박물관', NULL, '', 3, 'Y', 'SE', 'Museums');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0126', 'A01', '자연명소', NULL, '#1DDB16', 7, 'Y', 'SE', 'Nature');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012601', 'A0126', '산', NULL, '', 1, 'Y', 'SE', 'Mountains');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012602', 'A0126', '하천', NULL, '', 2, 'Y', 'SE', 'Streams');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0127', 'A01', '길', NULL, '#1DDB16', 8, 'Y', 'SE', 'Street');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012701', 'A0127', '테마거리', NULL, '', 1, 'Y', 'SE', 'Themes');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012702', 'A0127', '카페거리', NULL, '', 2, 'Y', 'SE', 'Cafés');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0128', 'A01', '산책', NULL, '#1DDB16', 9, 'Y', 'SE', 'Walking Tour');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012801', 'A0128', '공원', NULL, '', 1, 'Y', 'SE', 'Parks');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012803', 'A0128', '전망대', NULL, '', 2, 'Y', 'SE', 'Observatories');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A012804', 'A0128', '골목', NULL, '', 3, 'Y', 'SE', 'Alleys');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A05', NULL, '서울 위치', NULL, NULL, NULL, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0501', 'A05', '강남', NULL, NULL, 1, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050101', 'A0501', '강남구', NULL, NULL, 1, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050102', 'A0501', '강동구', NULL, NULL, 2, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050103', 'A0501', '강서구', NULL, NULL, 3, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050104', 'A0501', '관악구', NULL, NULL, 4, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050105', 'A0501', '구로구', NULL, NULL, 5, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050106', 'A0501', '금천구', NULL, NULL, 6, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050107', 'A0501', '동작구', NULL, NULL, 7, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050108', 'A0501', '서초구', NULL, NULL, 8, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050109', 'A0501', '송파구', NULL, NULL, 9, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050110', 'A0501', '양천구', NULL, NULL, 10, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050111', 'A0501', '영등포구', NULL, NULL, 11, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A0502', 'A05', '강북', NULL, NULL, 2, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050201', 'A0502', '강북구', NULL, NULL, 1, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050202', 'A0502', '광진구', NULL, NULL, 2, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050203', 'A0502', '노원구', NULL, NULL, 3, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050204', 'A0502', '도봉구', NULL, NULL, 4, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050205', 'A0502', '동대문구', NULL, NULL, 5, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050206', 'A0502', '마포구', NULL, NULL, 6, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050207', 'A0502', '서대문구', NULL, NULL, 7, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050208', 'A0502', '성동구', NULL, NULL, 8, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050209', 'A0502', '성북구', NULL, NULL, 9, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050210', 'A0502', '용산구', NULL, NULL, 10, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050211', 'A0502', '은평구', NULL, NULL, 11, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050212', 'A0502', '종로구', NULL, NULL, 12, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050213', 'A0502', '중구', NULL, NULL, 13, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('A050214', 'A0502', '중랑구', NULL, NULL, 14, 'Y', 'SE', 'temp');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0117', 'T01', '이벤트', NULL, NULL, 17, 'Y', 'SE', 'Event');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0118', 'T01', '여행을 더 달콤하게 🍯', NULL, NULL, 18, 'Y', 'SE', 'Let''s all share some tips!');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0119', 'T01', '쩝쩝 박사님들 주목해 주세요 🍽', NULL, NULL, 19, 'Y', 'SE', 'Attention, Gastronomes!');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0120', 'T01', '걸어서 서울 속으로 👣', NULL, NULL, 20, 'Y', 'SE', 'Walking into Seoul 👣');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0122', 'T01', '젠트립 추천 여행코스 📢', NULL, NULL, 22, 'Y', 'SE', 'Recommended Travel Courses by JenTrip 📢');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0123', 'T01', '인기 여행지 🔍', NULL, NULL, 23, 'Y', 'SE', 'Popular Tourist Spots 🔍');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('T0124', 'T01', '핫플 리스트 🤳', NULL, NULL, 24, 'Y', 'SE', 'Hot Place List 🤳');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('Z0203', 'Z02', '서울', 'SE', 'A05', 3, 'Y', 'SE', 'Seoul');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0109', 'C01', '추천', NULL, '#b37870', 1, 'Y', 'SE', 'Recommendations');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0110', 'C01', '자유분방', NULL, '#b37870', 3, 'Y', 'SE', 'Freewheeling');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0111', 'C01', '문화예술', NULL, '#b37870', 4, 'Y', 'SE', 'Culture and Arts');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0112', 'C01', '서울 속 자연', NULL, '#b37870', 5, 'Y', 'SE', 'Nature in Seoul ');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0114', 'C01', '사용자', NULL, '#b37870', 6, 'Y', 'SE', 'User');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0115', 'C01', '디지털노마드', NULL, '#b37870', 2, 'Y', 'SE', 'Digital Nomad');
INSERT INTO code_tb (cd, upper_cd, cd_nm, val1, val2, sort_order, use_yn, city_cd, cd_nm_eng) VALUES ('C0116', 'C01', 'K-콘텐츠', NULL, '#000000', 1, 'Y', 'JJ', 'K-contents');
