INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000120', '강보식', 'Kang Bosik', '2003년, 30대 중반 느닷없이 맞닥뜨린 큰아들의 소아급성백혈병을 통해 삶과 죽음 그리고 그 사이 를 직면하는 계기를 만났다. 그 이후 건강하고 행복한 삶의 의미를 찾아, 다니던 회사를 퇴직하고 숱한 시행착오 끝에 제주도로 정착하게 된지 10년이 훌쩍 넘었다. 30~40대를 통틀어 진행된 힘겨운 시행착오의 과정들이 세상에서의 관점에서 보면 일탈과 방황일 수 있겠지만, 그로인해 자신만의 꿈과 그 꿈을 이루어갈 수 있는 몸과 마음의 균형과 건강을 얻었다. 제주도라는 아름다운 자연에서의 혼자만의 시공간을 통해 자기자신을 깊게 만나고 사랑하고 하나 되는 성장의 세월을 경험으로 삼아, 자기만의 건강하고 행복한 삶의 가치를 추구하고 만들어가고자 하는 많은 사람들과 공유하기 위해, 여행사 ’더힐링아일랜드‘를 설립하고 현재 섬도보여행가이자 여행작가로서의 인생2막을 보내고 있다. 

더힐링아일랜드는 <제주휴식여행>, <제주힐링트레킹>, <제주명상캠프>, <제주다이어트캠프> 등 여행을 통한 새로운 라이프스타일의 추구와 변화를 목적으로 제주도를 중심으로 국내외 다양한 리트릿여행프로그램을 기획/운영하고 있다. ', '더힐링아일랜드', '대표', 'S0101', 'https://www.facebook.com/bskang67', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/ad500cb7-9bc1-4ef2-9cc6-b3289d5793d5.jpg', 'Huple003', STR_TO_DATE('2020-09-29 09:10:40.000', '%Y-%m-%d %H:%i:%s.%f'), 'Huple003', STR_TO_DATE('2020-09-29 09:23:04.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '2003년, 30대 중반 느닷없이 맞닥뜨린 큰아들의 소아급성백혈병을 통해 삶과 죽음 그리고 그 사이 를 직면하는 계기를 만났다. 그 이후 건강하고 행복한 삶의 의미를 찾아, 다니던 회사를 퇴직하고 숱한 시행착오 끝에 제주도로 정착하게 된지 10년이 훌쩍 넘었다. 30~40대를 통틀어 진행된 힘겨운 시행착오의 과정들이 세상에서의 관점에서 보면 일탈과 방황일 수 있겠지만, 그로인해 자신만의 꿈과 그 꿈을 이루어갈 수 있는 몸과 마음의 균형과 건강을 얻었다. 제주도라는 아름다운 자연에서의 혼자만의 시공간을 통해 자기자신을 깊게 만나고 사랑하고 하나 되는 성장의 세월을 경험으로 삼아, 자기만의 건강하고 행복한 삶의 가치를 추구하고 만들어가고자 하는 많은 사람들과 공유하기 위해, 여행사 ’더힐링아일랜드‘를 설립하고 현재 섬도보여행가이자 여행작가로서의 인생2막을 보내고 있다. 

더힐링아일랜드는 <제주휴식여행>, <제주힐링트레킹>, <제주명상캠프>, <제주다이어트캠프> 등 여행을 통한 새로운 라이프스타일의 추구와 변화를 목적으로 제주도를 중심으로 국내외 다양한 리트릿여행프로그램을 기획/운영하고 있다. ', 'The Healing Island', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000128', '이인경', 'Lee Ingyeong', '"일상과 삶을 더 소중하고 풍부하게 만들어주는 것이 여행이라고 생각해요. 낯선 장소와 사람, 문화를 접하고 다시 일상으로 돌아왔을 때 전에 없던 활력이 생겨요. 떠나기 전에는 알지 못했던 일상의 모습을 발견하고, 겪었던 일들이 서로 교차하면서 좀 더 폭넓은 생각을 하는 것 같아요. 그런 의미로 직접 떠나는 여행 뿐만 아니라 책과 영화를 통해서 얻는 경험 모두 저는 여행이라고 생각합니다."

섬 속의 섬 우도에서 우도를 기억할 수 있는 물건을 만드는 이인경 대표. 우도를 처음 만났던 순간, 어떤 것도 바라지 않고 그저 좋아하는 마음이 어린아이의 순수한 마음과 닮았던 것 같아 이름 짓게 된 ‘우도i’를 운영하며 그런 그녀의 마음을 우도에서 만난 인연들과 여행객들에게 나누고 있다.', '우도 i', '대표', 'S0102', 'https://www.instagram.com/jejuudoi/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/0d4cf409-d5d7-4b13-8d1a-aca8a7305349.jpg', 'Huple003', STR_TO_DATE('2020-11-26 10:50:27.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-07-26 13:47:11.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '"일상과 삶을 더 소중하고 풍부하게 만들어주는 것이 여행이라고 생각해요. 낯선 장소와 사람, 문화를 접하고 다시 일상으로 돌아왔을 때 전에 없던 활력이 생겨요. 떠나기 전에는 알지 못했던 일상의 모습을 발견하고, 겪었던 일들이 서로 교차하면서 좀 더 폭넓은 생각을 하는 것 같아요. 그런 의미로 직접 떠나는 여행 뿐만 아니라 책과 영화를 통해서 얻는 경험 모두 저는 여행이라고 생각합니다."

섬 속의 섬 우도에서 우도를 기억할 수 있는 물건을 만드는 이인경 대표. 우도를 처음 만났던 순간, 어떤 것도 바라지 않고 그저 좋아하는 마음이 어린아이의 순수한 마음과 닮았던 것 같아 이름 짓게 된 ‘우도i’를 운영하며 그런 그녀의 마음을 우도에서 만난 인연들과 여행객들에게 나누고 있다.', 'Udo i', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000119', '최현선', 'Choi Hyeonseon', '“여행은 ‘나를 찾는 과정’이라고 생각해요. 그리고 ‘나를 이해해 주는 과정’이기도 하고요. 일상적인 굴레에서 벗어나 새로운 경험을 할 때 나를 한 단계 더 알아갈 수 있게 된다고 생각해요. 여행이란 단어, 그리고 그것이 가지는 의미의 특별함 때문에 더욱 나를 위한 선택을 하게 되잖아요.”

금능해수욕장 앞 노을로 물든 외관이 인상적인 수공예 소품샵, ‘셔니인제주’를 운영중인 최현선 대표. 대부분 직접 개발하여 수공예로 제작한 제품들로 가득 채워놓은 공간에서 여행객들에게 새로운 경험을 만들어드리고자 노력하며, 어떻게 경험과 영감을 제품에 녹여낼까에 더 집중하고 있다.', '셔니인제주', '대표', 'S0102', 'https://www.instagram.com/sherny_in_jeju/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/a5125b63-6020-45ca-a554-dda1753f99e5.jpg', 'Huple003', STR_TO_DATE('2020-09-10 15:16:57.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-06-28 13:58:57.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 ‘나를 찾는 과정’이라고 생각해요. 그리고 ‘나를 이해해 주는 과정’이기도 하고요. 일상적인 굴레에서 벗어나 새로운 경험을 할 때 나를 한 단계 더 알아갈 수 있게 된다고 생각해요. 여행이란 단어, 그리고 그것이 가지는 의미의 특별함 때문에 더욱 나를 위한 선택을 하게 되잖아요.”

금능해수욕장 앞 노을로 물든 외관이 인상적인 수공예 소품샵, ‘셔니인제주’를 운영중인 최현선 대표. 대부분 직접 개발하여 수공예로 제작한 제품들로 가득 채워놓은 공간에서 여행객들에게 새로운 경험을 만들어드리고자 노력하며, 어떻게 경험과 영감을 제품에 녹여낼까에 더 집중하고 있다.', 'SHOWNU in Jeju Island', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000118', '유천규, 안경희', 'Yu Cheongyu, Ahn Gyeonghui', '“낯선 곳을 걸으며 보이는 풍경과 설레는 마음이 새로운데, 걸어온 길을 뒤돌아보면 좀 전과는 사뭇 다른 모습으로 다가오는 것이 새로워요. 언젠가 가봤던 곳을 다시 여행한다면 눈에 보이는 풍경은 비슷하겠지만 마음가짐이 새롭기 때문에 여행은 새로운 마음의 길을 걷는 것이라 생각해요.” 

물레 위에서 중심을 잡아 도자기를 만든다는 것은 마음의 중심을 잡는 것과 같은 일이라고 말하는 유천규, 안경희 부부. 그들은 한적한 시골마을인 하가리에서 흙이 주는 편안함과 즐거움을 누리며 ‘토예랑 도자기 공방’을 운영중이다.', '토예랑도자기공방', '부부', 'S0102', 'https://www.instagram.com/toyerangdoye/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/bb4c1b95-be8b-46a6-ab2d-6145106c4917.jpg', 'Huple003', STR_TO_DATE('2020-09-10 15:11:25.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-06-28 13:58:18.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“낯선 곳을 걸으며 보이는 풍경과 설레는 마음이 새로운데, 걸어온 길을 뒤돌아보면 좀 전과는 사뭇 다른 모습으로 다가오는 것이 새로워요. 언젠가 가봤던 곳을 다시 여행한다면 눈에 보이는 풍경은 비슷하겠지만 마음가짐이 새롭기 때문에 여행은 새로운 마음의 길을 걷는 것이라 생각해요.” 

물레 위에서 중심을 잡아 도자기를 만든다는 것은 마음의 중심을 잡는 것과 같은 일이라고 말하는 유천규, 안경희 부부. 그들은 한적한 시골마을인 하가리에서 흙이 주는 편안함과 즐거움을 누리며 ‘토예랑 도자기 공방’을 운영중이다.', 'Toyerang Pottery Workshop', 'husband and wife');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000117', '심용범', 'Sim Eungbeom', '“여행은 몸과 마음에 로즈마리 향 같은 걸 뿌리는 거라고 생각해요. 제품을 구매하시면 포장할 때 로즈마리를 붙여 드리거든요. 그리고는 “향기로운 하루가 되시라고요~”라고 말씀드려요. 눈으로만 보고 사진만 찍으러 다니는 관광 말고, 여유 있는 스케줄을 짜고 오감을 충족시킬 수 있는 여행을 좋아하는데, 일상에서 할 수 없는 경험들은 마치 삭막했던 일상에서 갑자기 로즈마리 향이 나서 기분이 좋아지는 느낌이 들게 해줘요.”

천연 인디고 염색으로 새로운 삶을 살고자 모든 자연이 가까이에 있는 제주에 정착한 심응범 대표. 천연 인디고 염색 기술과 색상의 매력에 푹 빠진 그는 카페보다는 인디고 염색에 포커스를 맞추고 싶은 ‘인디고 트리’를 운영하며 그와 어울리는 슬로우 라이프 스타일을 추구하는 삶을 살고 있다. ', '인디고트리', '대표', 'S0102', 'https://www.instagram.com/indigoterie/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/2b0cb6ba-3047-4189-bb0a-2d5b09231faa.jpg', 'Huple003', STR_TO_DATE('2020-09-10 15:04:05.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-06-28 13:57:46.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 몸과 마음에 로즈마리 향 같은 걸 뿌리는 거라고 생각해요. 제품을 구매하시면 포장할 때 로즈마리를 붙여 드리거든요. 그리고는 “향기로운 하루가 되시라고요~”라고 말씀드려요. 눈으로만 보고 사진만 찍으러 다니는 관광 말고, 여유 있는 스케줄을 짜고 오감을 충족시킬 수 있는 여행을 좋아하는데, 일상에서 할 수 없는 경험들은 마치 삭막했던 일상에서 갑자기 로즈마리 향이 나서 기분이 좋아지는 느낌이 들게 해줘요.”

천연 인디고 염색으로 새로운 삶을 살고자 모든 자연이 가까이에 있는 제주에 정착한 심응범 대표. 천연 인디고 염색 기술과 색상의 매력에 푹 빠진 그는 카페보다는 인디고 염색에 포커스를 맞추고 싶은 ‘인디고 트리’를 운영하며 그와 어울리는 슬로우 라이프 스타일을 추구하는 삶을 살고 있다. ', 'Indigotree', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000115', '김혜란', 'Kim Hyeran', '“여행은 ‘엉성하게 낭비하는 시간.’이라고 생각해요. 철저하게 세운 계획을 모두 지키며 하는 여행도 물론 보람 있지만, 힘든 일상을 마친 어느 날 그냥 문득 편하게 꺼내 웃으며 추억할 수 있는 엉성한 시간이 가장 나다운 여행 아닐까요?”

시간이 무척 느리게 가는 제주의 시골마을 종달리에서 단순하고 소소한 취향을 듬뿍 담은 작은 스테인드글라스 작업실과 쇼룸인 ‘단순’을 운영중인 김혜란대표. 단순하고 소소하게 살고 싶다는 삶의 목표처럼 유리 이외에도 드로잉과 영상 등 다양한 분야의 작업을 하며 지내고 있다.
', '종달리 단순', '대표', 'S0102', 'https://www.instagram.com/dansooon/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/a36364a8-e539-4681-93a1-01c2c67ffd19.jpg', 'Huple003', STR_TO_DATE('2020-09-09 17:31:00.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-06-24 14:29:44.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 ‘엉성하게 낭비하는 시간.’이라고 생각해요. 철저하게 세운 계획을 모두 지키며 하는 여행도 물론 보람 있지만, 힘든 일상을 마친 어느 날 그냥 문득 편하게 꺼내 웃으며 추억할 수 있는 엉성한 시간이 가장 나다운 여행 아닐까요?”

시간이 무척 느리게 가는 제주의 시골마을 종달리에서 단순하고 소소한 취향을 듬뿍 담은 작은 스테인드글라스 작업실과 쇼룸인 ‘단순’을 운영중인 김혜란대표. 단순하고 소소하게 살고 싶다는 삶의 목표처럼 유리 이외에도 드로잉과 영상 등 다양한 분야의 작업을 하며 지내고 있다.
', 'Bells are simple. Simple', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000127', '김성부', 'Kim Seongbu', '제주 돌담 사이에 숨겨진 카페 아체레타커피를 운영중인 김성부 대표. 로스팅부터 추출까지 직접 할 뿐만 아니라 건축을 전공했다는 그의 센스가 곳곳에서 느껴지는 이곳 아체레타는 단풍나무 숲이라는 뜻으로, 이름에 걸맞게 제주에서 보기 어려운 단풍나무가 심어져 있다.', '아체레타커피', '대표', 'S0102', 'https://www.instagram.com/acereta_coffee/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/f6983bb2-29da-41fc-ae2d-5aebc946e4ac.JPG', 'Huple003', STR_TO_DATE('2020-11-20 17:37:12.000', '%Y-%m-%d %H:%i:%s.%f'), 'Huple003', STR_TO_DATE('2020-11-20 18:40:03.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '제주 돌담 사이에 숨겨진 카페 아체레타커피를 운영중인 김성부 대표. 로스팅부터 추출까지 직접 할 뿐만 아니라 건축을 전공했다는 그의 센스가 곳곳에서 느껴지는 이곳 아체레타는 단풍나무 숲이라는 뜻으로, 이름에 걸맞게 제주에서 보기 어려운 단풍나무가 심어져 있다.', 'Acheretta Coffee', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000126', '미츠르, 할란', 'Mi Cheureu, Hallan', '조천읍 와흘리의 중심에서 작은 이자카야 0626와흘을 운영중인 할란, 미츠르 부부. 그들이 만난 날인 2006년 6월 26일이 가게 이름이 된 이곳은, 일본인인 미츠르 주인장 덕분인지 일본에 가보지 않았어도 일본을 그대로 옮겨 놓은 듯한 분위기를 느낄 수 있다.', '0626와흘', '부부', 'S0102', 'https://www.instagram.com/0626_waheul/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/e925438d-69cc-401a-9dd8-270c1064f6fe.jpg', 'Huple003', STR_TO_DATE('2020-11-20 17:34:27.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.ram', STR_TO_DATE('2022-10-17 16:51:04.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '', '0626 Waheul', 'husband and wife');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000116', '김정연', 'Kim Jeongyeon', '“여행을 통해 새로운 시각으로 새로운 것을 보고, 또 느낄 수 있으니까 일상으로부터의 환기가 되는 것 같아요.”

낡은 것을 좋아하는 생각 없는 찻집이라는 뜻의 ‘무상(無想) 찻집’을 운영 중인 김정연 대표. 그녀는 제철 재료를 이용해 차와 다식을 만드는 것으로 계절감을 느끼며 동네 골목 어귀에서 있는 듯 없는 듯 변함없이 웃으며 손님을 맞이하고 있다. ', '무상찻집', '대표', 'S0102', 'https://www.instagram.com/moosang_noidea/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/1e39c68e-8588-4580-80fd-7d33df3fdf6a.jpg', 'Huple003', STR_TO_DATE('2020-09-10 14:55:08.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-06-28 13:58:37.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행을 통해 새로운 시각으로 새로운 것을 보고, 또 느낄 수 있으니까 일상으로부터의 환기가 되는 것 같아요.”

낡은 것을 좋아하는 생각 없는 찻집이라는 뜻의 ‘무상(無想) 찻집’을 운영 중인 김정연 대표. 그녀는 제철 재료를 이용해 차와 다식을 만드는 것으로 계절감을 느끼며 동네 골목 어귀에서 있는 듯 없는 듯 변함없이 웃으며 손님을 맞이하고 있다. ', 'a free tea house', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000114', '장창언', 'Jang Changeon', '“여행은 삶이지요. 때론 힘들기도 하고 행복하기도 하고 결국은 하나의 추억으로 되새김질하는 그런 삶이요. 과거는 추억이고 미래는 상상인데 여행은 추억과 상상을 더욱 풍성하게 만들어 줍니다.“

식재료에 대한 믿음을 찾아 청수리에 정착하게 된 정창언 대표. 그는 세월의 흐름에 따라 재배되는 농산물들을 보고 느끼면서 바른 음식에 대한 생각을 갖게 되었고, 직접 농사를 짓고 수확하며 제주 출신 오너 쉐프로써 ‘피자 굽는 돌하르방’을 운영하며 10년째 로컬 식재료로 1m 길이의 피자를 만들고 있다. ', '피자굽는돌하르방', '대표', 'S0102', 'https://www.instagram.com/jangchangeon/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/f79e45ee-389f-473b-bef3-506b02ade090.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-07-26 13:46:01.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 삶이지요. 때론 힘들기도 하고 행복하기도 하고 결국은 하나의 추억으로 되새김질하는 그런 삶이요. 과거는 추억이고 미래는 상상인데 여행은 추억과 상상을 더욱 풍성하게 만들어 줍니다.“

식재료에 대한 믿음을 찾아 청수리에 정착하게 된 정창언 대표. 그는 세월의 흐름에 따라 재배되는 농산물들을 보고 느끼면서 바른 음식에 대한 생각을 갖게 되었고, 직접 농사를 짓고 수확하며 제주 출신 오너 쉐프로써 ‘피자 굽는 돌하르방’을 운영하며 10년째 로컬 식재료로 1m 길이의 피자를 만들고 있다. ', 'a stone statue of pizza roasting stone harubang', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000113', '김은정', 'Kim Eunjeong', '“여행은 나를 바라볼 수 있는 시간이에요. 현실에서는 생각해야 할 것들이 너무 많은데 그런 것들을 좀 내려놓고 온전히 나를 바라봐요. 여행을 통해서.”

맛 미(味), 친할 친(親)의 의미를 가진 ‘미친 부엌’에서 전반적인 일을 담당하고 있는 김은정 매니저. 하나같이 개성이 강한 미친 사람들과 미치게 바쁘게 일하고 있다는 그녀는 당일치기로 어디든 다녀올 수 있는 제주에서 무념무상 올레길을 걷는 것을 즐긴다. ', '미친부엌', '매니저', 'S0102', 'https://www.instagram.com/geon_ah_kong', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/e577e623-4bcc-44c2-a5f3-0d748b5113ea.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-07-26 13:45:48.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 나를 바라볼 수 있는 시간이에요. 현실에서는 생각해야 할 것들이 너무 많은데 그런 것들을 좀 내려놓고 온전히 나를 바라봐요. 여행을 통해서.”

맛 미(味), 친할 친(親)의 의미를 가진 ‘미친 부엌’에서 전반적인 일을 담당하고 있는 김은정 매니저. 하나같이 개성이 강한 미친 사람들과 미치게 바쁘게 일하고 있다는 그녀는 당일치기로 어디든 다녀올 수 있는 제주에서 무념무상 올레길을 걷는 것을 즐긴다. ', 'Crazy kitchen', 'Manager');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000112', '김혜광', 'Kim Hyegwang', '“몰랐을 땐 낯설지만 아는 순간 행복한 것이 여행이라고 생각해요. 제주에 와서 행복을 맛본 후부터 여행을 다니게 됐거든요.”


금능해수욕장 근처에서 해물라면 가게인 ‘금능상회’를 운영 중인 김혜광대표. 그는 제주에서 비로소 여행의 맛을 깨닫고 행복한 제주 생활을 즐기며 수제 우유 가게인 ‘김씨사생활’을 리뉴얼 오픈 준비 중이다. ', '김씨사생활', '대표', 'S0102', 'https://www.instagram.com/jeju__kkk', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/25fd9a03-36bc-4ed2-a155-50aa66d58a61.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-07-26 13:46:11.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“몰랐을 땐 낯설지만 아는 순간 행복한 것이 여행이라고 생각해요. 제주에 와서 행복을 맛본 후부터 여행을 다니게 됐거든요.”


금능해수욕장 근처에서 해물라면 가게인 ‘금능상회’를 운영 중인 김혜광대표. 그는 제주에서 비로소 여행의 맛을 깨닫고 행복한 제주 생활을 즐기며 수제 우유 가게인 ‘김씨사생활’을 리뉴얼 오픈 준비 중이다. ', 'Kim`s private life', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000111', '김정미,김현승', 'Kim Jeongmi, Kim Hyeonseung', '“여행은 인생의 대항해 같아요. 어떤 일이 벌어질지 예측할 수 없는 모험이자 탐험이고, 그게 나의 사상과 역사를 바꾸는 일일지도 모른다는 생각이 들어요.”

알뜨르비행장 근처의 산방산, 격납고, 모슬봉 모두 UFO모양 같아 보였고, 마침 그들의 계획적이지 못했던 상황이 모슬포에 불시착 한 것 같아서 이름 짓게 된 ‘비행접시’. 그 곳에서 김정미, 김현승 부부는 지나가는 자전거 라이더들과 올레길 탐방객들을 위한 아주 작은 카페이자 퍼스널 짐을 운영중이다. ', '비행접시', '부부', 'S0102', 'https://www.instagram.com/biheangjeobsi/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/48008631-59a7-402d-9222-f676ec214e60.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-06-28 13:56:35.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 인생의 대항해 같아요. 어떤 일이 벌어질지 예측할 수 없는 모험이자 탐험이고, 그게 나의 사상과 역사를 바꾸는 일일지도 모른다는 생각이 들어요.”

알뜨르비행장 근처의 산방산, 격납고, 모슬봉 모두 UFO모양 같아 보였고, 마침 그들의 계획적이지 못했던 상황이 모슬포에 불시착 한 것 같아서 이름 짓게 된 ‘비행접시’. 그 곳에서 김정미, 김현승 부부는 지나가는 자전거 라이더들과 올레길 탐방객들을 위한 아주 작은 카페이자 퍼스널 짐을 운영중이다. ', 'flying saucer', 'husband and wife');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000110', '김혜경', 'Kim Hyegyeong', '', '엘림홈', '대표', 'S0107', 'https://www.instagram.com/elim_home/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/a4c133f3-30ff-408a-9731-0a2c5954d48d.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '', 'Elem Home', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000109', '황태준', 'Hwang Taejun', '“여행은 제2의 나 자신을 찾을 수 있게 해줘요. 보지 못했던 세상을 보면서, 사회에서 가르쳐 주지 않는 무언가를 배우면서, 그렇게 오직 나만을 위한 시간을 여행을 통해 보내고 있어요.”

어떤 곳 보다 더 반갑게 맞아 주었고 고향보다 더 고향 같은 느낌을 주었던 제주와 함께 살아간다는 것 자체가 큰 즐거움이라는 제주에서 가장 어린 사장, 황태준 대표. 그는 ‘토시오의 다락방’에서 추억을 요리하며 잊지 못할 추억과 분위기를 선물하고 있다.  ', '토시오의 다락방', '대표', 'S0102', 'https://www.instagram.com/toshio_2020/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/fe76e4af-6aa0-461f-9735-6b5f8aebcd9f.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-06-28 13:58:28.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 제2의 나 자신을 찾을 수 있게 해줘요. 보지 못했던 세상을 보면서, 사회에서 가르쳐 주지 않는 무언가를 배우면서, 그렇게 오직 나만을 위한 시간을 여행을 통해 보내고 있어요.”

어떤 곳 보다 더 반갑게 맞아 주었고 고향보다 더 고향 같은 느낌을 주었던 제주와 함께 살아간다는 것 자체가 큰 즐거움이라는 제주에서 가장 어린 사장, 황태준 대표. 그는 ‘토시오의 다락방’에서 추억을 요리하며 잊지 못할 추억과 분위기를 선물하고 있다.  ', 'Toshio`s attic', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000108', '문비', 'Mun Bi', '“여행은 20대에 즐길 수 있는 가장 짜릿한 취미라고 생각해요. 20대엔 돈이 없잖아요. 열심히 모아서 한방에 쓰는 쾌감이 정말 짜릿해요.”

‘예쁜 것’을 좋아하는 사람. 사진을 시작하게 된 이유도 그러한 것들을 담고 싶어서일 만큼 예쁜 것을 좋아하는 문비 작가는, 그녀가 찍은 스냅 사진들로 ‘달의정원’을 가꾸고 있는 중이다. 외에도 밴드 ‘봄동’에서 보컬리스트로, 피아노 선생님으로 살며 하루하루 제주를 사랑하고 있다.', '달의정원', '작가', 'S0102', 'https://www.instagram.com/moonsgarden_/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/51655297-dac9-404b-b20f-4221f890dd3b.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.ram', STR_TO_DATE('2021-06-28 10:22:59.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 20대에 즐길 수 있는 가장 짜릿한 취미라고 생각해요. 20대엔 돈이 없잖아요. 열심히 모아서 한방에 쓰는 쾌감이 정말 짜릿해요.”

‘예쁜 것’을 좋아하는 사람. 사진을 시작하게 된 이유도 그러한 것들을 담고 싶어서일 만큼 예쁜 것을 좋아하는 문비 작가는, 그녀가 찍은 스냅 사진들로 ‘달의정원’을 가꾸고 있는 중이다. 외에도 밴드 ‘봄동’에서 보컬리스트로, 피아노 선생님으로 살며 하루하루 제주를 사랑하고 있다.', 'the moon garden', 'Writer');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000107', '조현태', 'Cho Hyeontae', '“일상에서 유튜브를 통해 여행을 해요. 랜선 여행 같은 거죠. 외국인 구독자가 더 많은데 그분들과 소통하며 여러 나라의 색을 알게 되고, 새로운 메뉴를 개발할 때 참고하기도 하고요.”

일출과 일몰을 하루에 다 볼 수 있는 것이 제주의 매력이라는 조현태 대표. 그는 아내와 함께 여행 다니는 것을 좋아하여 짓게 된 이름인 브런치 카페 위더스트래블(With Us Travel)을 운영하며, 이곳에서 맛있는 브런치와 제2의 직업인 유튜브 콘텐츠들을 만들고 있다. ', '위더스트래블', '대표', 'S0102', 'https://www.youtube.com/channel/UCabdatPVZIBNH2QSWxzbvow', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/76d86c20-f223-4ddf-98df-f255d2945bf0.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-06-28 13:56:25.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“일상에서 유튜브를 통해 여행을 해요. 랜선 여행 같은 거죠. 외국인 구독자가 더 많은데 그분들과 소통하며 여러 나라의 색을 알게 되고, 새로운 메뉴를 개발할 때 참고하기도 하고요.”

일출과 일몰을 하루에 다 볼 수 있는 것이 제주의 매력이라는 조현태 대표. 그는 아내와 함께 여행 다니는 것을 좋아하여 짓게 된 이름인 브런치 카페 위더스트래블(With Us Travel)을 운영하며, 이곳에서 맛있는 브런치와 제2의 직업인 유튜브 콘텐츠들을 만들고 있다. ', 'Wither Travel', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000106', '', '', '', '에곤', '', 'S0107', 'https://www.instagram.com/jeju_egon/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/a4c133f3-30ff-408a-9731-0a2c5954d48d.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '', 'Egon', '');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000105', '', '', '', '꽃향유', '', 'S0107', 'https://www.instagram.com/rhc782000/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/acd40d8b-ea34-4414-9775-7d209cd18877.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '', 'Flower fragrance', '');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000104', '이상일, 오미희', 'Lee Sangil, Oh Mihui', '“여행은 지치지 않고 앞으로 달려나갈 수 있도록 원동력이 되어주는, 열심히 살아온 나에게 주는 선물 같아요.”

이름도 예쁜 연꽃마을, 애월 하가리에서 행복한 하루하루를 보내고 있다는 이상일, 오미희 부부. 그들은 밝지 않아도 어두운 밤 은은하게 세상을 비추는 달빛처럼 조용하고 따뜻한 가게가 되고 싶은 마음을 담아, 돈까스집 ‘연월’을 운영하고 있다.', '연월', '부부', 'S0102', 'https://www.instagram.com/jeju_yeonwol/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/404cba9a-29d8-482d-8b6a-ce2fae3d2d54.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-07-26 13:36:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 지치지 않고 앞으로 달려나갈 수 있도록 원동력이 되어주는, 열심히 살아온 나에게 주는 선물 같아요.”

이름도 예쁜 연꽃마을, 애월 하가리에서 행복한 하루하루를 보내고 있다는 이상일, 오미희 부부. 그들은 밝지 않아도 어두운 밤 은은하게 세상을 비추는 달빛처럼 조용하고 따뜻한 가게가 되고 싶은 마음을 담아, 돈까스집 ‘연월’을 운영하고 있다.', 'year and month', 'husband and wife');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000103', '박지숙', 'Park Jisuk', '“여행은 모든 소중한 사람과의 추억과 이야기를 만드는 소중한 과정이에요.”

그림을 그리는 ‘그림작업실’과, 쿠키를 굽는 제로웨이스트샵 ‘바사삭작업실’이 있는 ‘이야기창고’를 운영중인 박지숙 대표. 그녀는 매년 8월이면 연꽃이 활짝 피는 연화지로 유명한 애월 하가리의 작은 동네에서 많은 사람들과 작품을 만들고 감상하며 함께 소통할 수 있는 공간을 만들고 있다. ', '이야기창고', '대표', 'S0102', 'https://www.instagram.com/jeju_story_art/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/c3c242c9-aa19-438b-851f-7aa43aa97123.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-07-26 13:44:59.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '“여행은 모든 소중한 사람과의 추억과 이야기를 만드는 소중한 과정이에요.”

그림을 그리는 ‘그림작업실’과, 쿠키를 굽는 제로웨이스트샵 ‘바사삭작업실’이 있는 ‘이야기창고’를 운영중인 박지숙 대표. 그녀는 매년 8월이면 연꽃이 활짝 피는 연화지로 유명한 애월 하가리의 작은 동네에서 많은 사람들과 작품을 만들고 감상하며 함께 소통할 수 있는 공간을 만들고 있다. ', 'a story warehouse', 'CEO');
INSERT INTO interviewee_tb (interviewee_id, kor_nm, eng_nm, interviewee_desc, interviewee_corp, interviewee_position, link_cd, link_url, rpsnt_image_url, create_id, create_dt, update_id, update_dt, state, city_cd, interviewee_desc_eng, interviewee_corp_eng, interviewee_position_eng) VALUES ('INTERVIEWEE000000102', '정현덕', 'Jeong Hyeondeok', '"구본형 작가의 ‘떠남과 만남’에서 읽은 구절로 대신합니다.
‘여행은 다른 사람이 덮던 이불을 덮고 자는 것이다. 그리고 다른 사람이 쓰던 밥그릇과 숟가락으로 밥을 먹는 것이다. 온갖 사람들이 다녀간 낡은 여관방 벽지 앞에서 옷을 갈아입는 것이다. 그리고 그 낡은 벽지가 기억하고 있는 수많은 사람들의 이야기 속에 자신의 이야기를 더하는 것이다. 그럼으로써 자신을 다른 사람에게 보내고, 다른 사람을 자신 속으로 받아들이는 것이다.’"


이웃들이 좋은 책을 많이 읽고 책을 통해 즐거움과 위안, 행복을 느꼈으면 하는 바람을 품고 ‘그리고 서점’ 책방을 운영중인 정현덕 대표. 어릴 적 꿈이었던 서점 주인이 되어, 경계 없는 마을학교를 꿈꾸는 애월교육협동조합 ‘이음’의 조합원으로 이음 작은 도서관의 사서 역할도 하고 있다.
', '그리고서점', '대표', 'S0102', 'https://www.instagram.com/and_bookshop/', 'https://file-upload-bucket.kr.object.ncloudstorage.com/upload-folder/1df3416b-3ebe-471b-8106-6388787be001.jpg', 'Huple001', STR_TO_DATE('2020-08-25 11:13:31.000', '%Y-%m-%d %H:%i:%s.%f'), 'huple.lch', STR_TO_DATE('2021-06-28 13:59:07.000', '%Y-%m-%d %H:%i:%s.%f'), 'S', 'JJ', '"구본형 작가의 ‘떠남과 만남’에서 읽은 구절로 대신합니다.
‘여행은 다른 사람이 덮던 이불을 덮고 자는 것이다. 그리고 다른 사람이 쓰던 밥그릇과 숟가락으로 밥을 먹는 것이다. 온갖 사람들이 다녀간 낡은 여관방 벽지 앞에서 옷을 갈아입는 것이다. 그리고 그 낡은 벽지가 기억하고 있는 수많은 사람들의 이야기 속에 자신의 이야기를 더하는 것이다. 그럼으로써 자신을 다른 사람에게 보내고, 다른 사람을 자신 속으로 받아들이는 것이다.’"


이웃들이 좋은 책을 많이 읽고 책을 통해 즐거움과 위안, 행복을 느꼈으면 하는 바람을 품고 ‘그리고 서점’ 책방을 운영중인 정현덕 대표. 어릴 적 꿈이었던 서점 주인이 되어, 경계 없는 마을학교를 꿈꾸는 애월교육협동조합 ‘이음’의 조합원으로 이음 작은 도서관의 사서 역할도 하고 있다.
', 'And a bookstore', 'CEO');
