ALTER TABLE tour_place_tb ADD CONSTRAINT pk PRIMARY KEY (tour_id,place_id);
ALTER TABLE popular_keyword_tb ADD CONSTRAINT pk PRIMARY KEY (seq_no);
ALTER TABLE plan_notice_tb ADD CONSTRAINT pk_plan_notice_tb_plan_id_seq_no PRIMARY KEY (plan_id,seq_no);
ALTER TABLE rentcar_tb ADD CONSTRAINT pk PRIMARY KEY (id);
ALTER TABLE location_info_tb ADD CONSTRAINT pk PRIMARY KEY (location_id);
ALTER TABLE post_tb ADD CONSTRAINT pk_post01_tb PRIMARY KEY (post_id);
ALTER TABLE map_equipment_tb ADD CONSTRAINT pk_map_equipment_tb PRIMARY KEY (equip_type,equip_seq_no);
ALTER TABLE plan_day_schedule_tb ADD CONSTRAINT pk PRIMARY KEY (plan_id,plan_seq_no,schedule_seq_no);
ALTER TABLE ta_black_section_path_tb ADD CONSTRAINT pk PRIMARY KEY (seq_no,sort_order);
ALTER TABLE tour_tb ADD CONSTRAINT pk PRIMARY KEY (tour_id);
ALTER TABLE area_rise_set_tb ADD CONSTRAINT pk_area_rise_set_tb_location_loc_date PRIMARY KEY (location,loc_date);
ALTER TABLE ta_black_section_tb ADD CONSTRAINT pk_ta_black_section_tb_seq_no PRIMARY KEY (seq_no);
ALTER TABLE hotel_tb ADD CONSTRAINT pk PRIMARY KEY (id);
ALTER TABLE global_weather_tb ADD CONSTRAINT pk_global_weather_tb_city_id_date_time PRIMARY KEY (city_id,date_time);
ALTER TABLE plan_day_tb ADD CONSTRAINT pk PRIMARY KEY (plan_id,plan_seq_no);
ALTER TABLE season_need_contents_rate_tb ADD CONSTRAINT pk PRIMARY KEY (season_cd);
ALTER TABLE interviewee_link_tb ADD CONSTRAINT pk PRIMARY KEY (seq_no,link_id);
ALTER TABLE category_post_tb ADD CONSTRAINT pk_category_post_tb PRIMARY KEY (category_cd,seq_no);
ALTER TABLE local_brand_grade_tb ADD CONSTRAINT pk PRIMARY KEY (place_id);
ALTER TABLE course_day_tb ADD CONSTRAINT pk_course_tb PRIMARY KEY (course_id,plan_seq_no);
ALTER TABLE keyword_place_tb ADD CONSTRAINT pk PRIMARY KEY (seq_no);
ALTER TABLE tour_date_tb ADD CONSTRAINT pk PRIMARY KEY (tour_id,tour_date);
ALTER TABLE place99_tb ADD CONSTRAINT pk_place99_tb PRIMARY KEY (start_id,end_id);
ALTER TABLE keyword_tb ADD CONSTRAINT pk PRIMARY KEY (keyword_id);
ALTER TABLE interviewee_tb ADD CONSTRAINT pk PRIMARY KEY (interviewee_id);
ALTER TABLE map_medical_tb ADD CONSTRAINT pk_map_medical_tb PRIMARY KEY (medi_type,medi_seq_no);
ALTER TABLE local_brand_post_tb ADD CONSTRAINT pk PRIMARY KEY (post_id);
ALTER TABLE customer_tb ADD CONSTRAINT pk_customer_tb PRIMARY KEY (customer_id);
ALTER TABLE course_tb ADD CONSTRAINT pk_course_tb PRIMARY KEY (course_id);
ALTER TABLE mid_land_fcst ADD CONSTRAINT pk_mid_land_fcst_fcst_date PRIMARY KEY (fcst_date,reg_id);
ALTER TABLE plan_member_tb ADD CONSTRAINT pk PRIMARY KEY (plan_id,seq_no);
ALTER TABLE image_info_tb ADD CONSTRAINT pk PRIMARY KEY (image_id,seq_no);
ALTER TABLE place03_tb ADD CONSTRAINT pk_place03_tb PRIMARY KEY (place_id);
ALTER TABLE tide_obs_pre_tab ADD CONSTRAINT pk_tide_obs_pre_tab_obs_code_tph_date_seq_no PRIMARY KEY (obs_code,tph_date,seq_no);
ALTER TABLE ma_black_spot_tb ADD CONSTRAINT pk_ma_black_spot_tb_seq_no PRIMARY KEY (seq_no);
ALTER TABLE village_fcst ADD CONSTRAINT pk PRIMARY KEY (fcst_date,fcst_time,category,nx,ny);
ALTER TABLE place04_tb ADD CONSTRAINT pk_place03_tb PRIMARY KEY (place_id,seq_no);
ALTER TABLE place02_tb ADD CONSTRAINT pk_place02_tb PRIMARY KEY (place_id,seq_no);
ALTER TABLE local_brand_grade_history_tb ADD CONSTRAINT pk PRIMARY KEY (seq_no);
ALTER TABLE ultra_srt_fcst ADD CONSTRAINT pk_ultra_srt_fcst_fcst_date_fcst_time_category_nx_ny PRIMARY KEY (fcst_date,fcst_time,category,nx,ny);
ALTER TABLE local_brand_fac_info_tb ADD CONSTRAINT pk PRIMARY KEY (place_id,seq_no);
ALTER TABLE uv_idx_tb ADD CONSTRAINT pk PRIMARY KEY (area_code,fcst_date);
ALTER TABLE local_brand_place_tb ADD CONSTRAINT pk PRIMARY KEY (place_id);
ALTER TABLE plan_tb ADD CONSTRAINT pk PRIMARY KEY (plan_id);
ALTER TABLE place01_tb ADD CONSTRAINT pk_place01_tb PRIMARY KEY (place_id);
ALTER TABLE ba_black_spot_tb ADD CONSTRAINT pk_ba_black_spot_tb_seq_no PRIMARY KEY (seq_no);
ALTER TABLE home_post_tb ADD CONSTRAINT pk_home_post_tb_seq_no PRIMARY KEY (seq_no);
ALTER TABLE place_visit_cnt_tb ADD CONSTRAINT pk PRIMARY KEY (place_id);
ALTER TABLE local_brand_place_visit_cnt_tb ADD CONSTRAINT pk PRIMARY KEY (place_id);
ALTER TABLE ta_black_spot_tb ADD CONSTRAINT pk_ta_black_spot_tb_seq_no PRIMARY KEY (seq_no);
ALTER TABLE lodge_fac_info_tb ADD CONSTRAINT pk_lodge_fac_info_tb PRIMARY KEY (seq_no,lodge_id);
ALTER TABLE sa_black_spot_tb ADD CONSTRAINT pk_sa_black_spot_tb_seq_no PRIMARY KEY (seq_no);
ALTER TABLE spot_tb ADD CONSTRAINT pk PRIMARY KEY (spot_id);
ALTER TABLE kma_area_code ADD CONSTRAINT pk_kma_area_code_code PRIMARY KEY (code);
ALTER TABLE honey_tip_tb ADD CONSTRAINT pk_tip01_tb PRIMARY KEY (tip_id);
ALTER TABLE lodge_tb ADD CONSTRAINT pk_lodge_tb PRIMARY KEY (lodge_id);
ALTER TABLE faq_tb ADD CONSTRAINT pk_faq_tb_seq_no PRIMARY KEY (seq_no);
ALTER TABLE lodge_link_info_tb ADD CONSTRAINT pk_lodge_link_info_tb PRIMARY KEY (lodge_id);
ALTER TABLE mid_ta_fcst ADD CONSTRAINT pk_mid_ta_fcst_fcst_date PRIMARY KEY (fcst_date,area_code);
ALTER TABLE ultra_srt_ncst ADD CONSTRAINT pk_ultra_srt_ncst_base_date_base_time_category_nx_ny PRIMARY KEY (base_date,base_time,category,nx,ny);
ALTER TABLE course_day_schedule_tb ADD CONSTRAINT pk_course_schedule_tb PRIMARY KEY (course_id,plan_seq_no,schedule_seq_no);
ALTER TABLE map_charge_tb ADD CONSTRAINT pk_map_charge_tb PRIMARY KEY (chrg_type,chrg_seq_no);
ALTER TABLE map_safety_tb ADD CONSTRAINT pk_map_safety_tb PRIMARY KEY (safe_type,safe_seq_no);

CREATE INDEX i_popular_keyword_tb_city_cd_language ON popular_keyword_tb(city_cd,`language`);
CREATE INDEX i_post_content_tb_post_id_seq ON post_content_tb(post_id,seq);
CREATE INDEX i_post_tb_place_id ON post_tb(place_id);
CREATE INDEX idx_map_equipment_tb ON map_equipment_tb(equip_type,equip_lat,equip_lng);
CREATE INDEX i_global_weather_tb_date_time ON global_weather_tb(date_time);
CREATE INDEX i_local_brand_post_content_tb_post_id_seq ON local_brand_post_content_tb(post_id,seq);
CREATE INDEX idx_map_medical_ttb ON map_medical_tb(medi_type,medi_lat,medi_lng);
CREATE INDEX i_local_brand_post_tb_place_id ON local_brand_post_tb(place_id);
CREATE INDEX i_course_tb_plan_id ON course_tb(plan_id);
CREATE INDEX i_plan_member_tb_customer_id_plan_leave_dt ON plan_member_tb(customer_id,plan_leave_dt);
CREATE INDEX i_place02_tb_seq_no ON place02_tb(seq_no);
CREATE INDEX i_post_dt_tb_gubun_post_id ON post_dt_tb(gubun,post_id);
CREATE INDEX i_plan_tb_course_id ON plan_tb(course_id);

CREATE UNIQUE INDEX u_plan_tb_plan_id ON plan_tb(plan_id);
CREATE INDEX i_place01_tb_place_loct_cd1 ON place01_tb(place_loct_cd1);
CREATE INDEX i_home_post_tb_gubun_post_id_city_cd_language ON home_post_tb(gubun,post_id,city_cd,`language`);
CREATE INDEX i_ai_except_word_tb_use_yn ON ai_except_word_tb(use_yn);
CREATE INDEX i_kma_area_code_city_cd ON kma_area_code(city_cd);
CREATE INDEX i_honey_tip_tb_place_id_state ON honey_tip_tb(place_id,state);
CREATE INDEX i_course_day_schedule_tb_place_id ON course_day_schedule_tb(place_id);

CREATE INDEX i_course_day_schedule_tb_post_id ON course_day_schedule_tb(post_id);
CREATE INDEX idx_map_charge_tb ON map_charge_tb(chrg_type,chrg_lat,chrg_lng);
CREATE INDEX idx_map_safety_tb ON map_safety_tb(safe_type,safe_lat,safe_lng);

